### PR TITLE
Strip quotes from CLI input on Windows

### PR DESCRIPTION
**Pull request by kurtextrem**
Fixes DmitrySoshnikov/regexp-tree#84

### CODE REVIEW

**Comment by kurtextrem** [comment]
I'm currently trying to squash the commits. Hang on, I'm new to that.

**Comment by kurtextrem** [comment]
I can't wrap my head around this, sorry. Do you have any experience in that? It just doesn't remove the previous commits (and adds a merge commit)

**Comment by kurtextrem** [comment]
Okay I did it :) I hope that works.

**Comment by DmitrySoshnikov** [comment]
Perfect, thanks! 👍 

(in general, several commits are also OK, and often are considered even better, than merging changes in one commit; I'm fine with both approaches, thanks again)

**Comment by kurtextrem** [comment]
I thought an indentation commit shouldn't be in :D

**Pull request merged**
