### PR TITLE
WIP: Number nested groups correctly

### PR DESCRIPTION
**Pull request by davisjam**
Towards #164.

1. Possibly over-engineering. Not sure if there's a need for a "PostParsingPass" concept. But I think it's cleaner.

2. As noted in 5d3682b, I'm not sure how to construct the list of nodes in a way that enables the re-numbering we want, *without* traversing the full tree.

```
=======================
( a ( b ( c ) ) ) d ( e)

Visit order:
3   2   1              4

Desired number order:
1   2   3              4

=======================
( a ) ( b ) ( c ) ( d )

Visit order:
1     2       3      4

Desired number order:
1     2       3      4

=====================

Q: How do we tell whether we are nested or not
during visits?
```

Without a pre/post-hook on parsing steps, I don't see how to address this in the parser at the moment.

Except, of course, via an AST walk.
How concerned are you about the cost of an AST walk? Honestly I can't imagine it will be too expensive.

### CODE REVIEW

**Comment by DmitrySoshnikov** [comment]
@davisjam, awesome, thanks; I'll try take a closer look at the PR soon.

**Comment by davisjam** [comment]
>  I'm not sure how to construct the list of nodes in a way that enables the re-numbering we want, *without* traversing the full tree.

Suppose we did a single walk after parsing, to assign the "walk indices" of the nodes. Then each PostParsingPass could sort the nodes of interest by walk index before processing, providing a well-defined traversal order with O(number of nodes of interest) for each pass.

The walk index is the ordering needed for group renumbering so this would work for #164.
Do you see a need for other PostParsingPass's?

**Comment by DmitrySoshnikov** [comment]
I've just recall that I had the https://github.com/DmitrySoshnikov/syntax/issues/48 opened for a while. This will allow analyzing a shifted token in the parser.

But now I'm thinking about adding a generic `onToken` event to the tokenizer, see the https://github.com/DmitrySoshnikov/syntax/issues/62. This allow subscribing, and checking if the parsed token is `L_PAREN`, i.e. `(`, and count.

```js
let totalGroups = 0;
let currentGroupNumber = 0;

yyparse.onParseBegin = (string, lexer) => {
  ...
  currentGroupNumber = 0;
  totalGroups = 0;
};

// Count left parens of capturing groups since
// In the /(((a)b)c)/, the "a" should be 3, "ab" - 2, "abc" - 1
yyparse.tokenizer.onToken = token => {
  if (token.type === 'L_PAREN' || token.type === 'NAMED_CAPTURE_GROUP') {
    currentGroupNumber++;
    totalGroups++;
  }
};
```

Then [when we have parsed the group](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/parser/regexp.bnf#L777-L806), we do:

```js
currentGroupNumber--;

if (currentGroupNumber === 0) {
   currentGroupNumber = totalGroups;
}
```

So by the time it reaches the very nested group, the `currentGroupNumber` should be 3, then it decreases it, going up, until it reaches `0`. Then it resets to the total number, so in the:

```
/(((a)b)c)(d)/
``` 

the `"d"` will correctly be `4`.

This should allow us tracking the parens w/o doing post-processing.

**Comment by davisjam** [comment]
Looks promising, I will take a look.

**Comment by DmitrySoshnikov** [comment]
Cool! Make sure to use exactly `yyparse.onShift` hook, and not `yy.tokenizer.onToken`, since `onToken` happens prior the previous reduce, and it's hard to track the parens count.

**Comment by DmitrySoshnikov** [comment]
OK, I've added the fix in https://github.com/DmitrySoshnikov/regexp-tree/commit/6709afd1192012e6caac60b4d4d8d38c646bb87a. @davisjam, please let me know if you see any issues. Closing this one.

**Comment by davisjam** [comment]
Looks great. Sorry this fell off my radar.

**Pull request closed without merging**
